// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;

export function SelectFile():Promise<main.FileInfo>;

export function SelectOutputDir():Promise<string>;

export function Split(arg1:string,arg2:string,arg3:string):Promise<main.SplitResult>;
